# Generated by Django 5.2.1 on 2025-05-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
                (
                    "emoji",
                    models.CharField(default="", max_length=10, verbose_name="Эмодзи"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Up_Fle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/originals/%Y/%m/%d/",
                        verbose_name="Загруженный файл",
                    ),
                ),
                (
                    "processed_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/processed/%Y/%m/%d/",
                        verbose_name="Обработанный файл",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Загруженный файл",
                "verbose_name_plural": "Загруженные файлы",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                ("identifier", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название подкатегории"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание подкатегории")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="polls.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
    ]
